name: ocrthypdf
title: OCRthyPDF Essentials
base: core18 # the base snap is the execution environment for this snap
adopt-info: ocrthypdf
summary: Make your PDF files text-searchable (A GUI for OCRmyPDF)
description: |
  This is a basic user interface for the command line tool OCRmyPDF. 
  It's main purpose is to provide users that are not used to command 
  line tools easy access to OCRmyPDF's basic features.  
  You can use it to make PDF files that contain images with text 
  (e. g. after scanning) searchable by adding an invisible text layer.
  If you like the results created with OCRthyPDF but need more flexibility 
  I suggest you give OCRmyPDF a try on the command line. 
license: AGPL-3.0
icon: gui/ocrthypdf.svg 
compression: lzo 
grade: stable # 'stable' 'devel'
confinement: strict # 'strict' 'devmode'
architectures: [amd64]
environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
    #LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/
    GS_LIB: $SNAP/usr/share/ghostscript/9.26/Resource/Init 
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.26/Resource/Font
    PATH: $PATH:$SNAP/usr/lib/jvm/java-8-openjdk-amd64/bin
    
apps:
  ocrthypdf:
    command: bin/snapcraft-preload python3 $SNAP/code/OCRthyPDF.py
    command-chain: [bin/debian-multiarch-triplet-provider-launch, bin/tcltk-launch]
    desktop: $SNAPCRAFT_PROJECT_DIR/gui/ocrthypdf.desktop
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
    
parts:
  get-source:
    plugin: dump
    source: https://github.com/digidigital/OCRthyPDF-Essentials.git
  snapcraft-preload:
      source: https://github.com/sergiusens/snapcraft-preload.git
      plugin: cmake
      build-packages:
        - on amd64:
          - gcc-multilib
          - g++-multilib
      stage-packages:
      - lib32stdc++6  
  tcltk-launch:
    plugin: nil
    stage-snaps: [tcltk-launch]
  debian-multiarch-triplet-provider-launch:
    plugin: nil
    stage-snaps: [debian-multiarch-triplet-provider-launch]
  ocrthypdf:
    plugin: python
    source: https://github.com/digidigital/OCRthyPDF-Essentials.git
    source-type: git
    python-packages: [PySimpleGUI, ocrmypdf, setuptools-rust, zxing, pikepdf]
    stage-packages: [python3-tk, tcl, ghostscript, icc-profiles-free, liblept5, libxml2, pngquant, tesseract-ocr-all, unpaper, qpdf, zlib1g, imagemagick, openjdk-8-jre] 
    build-packages: [rustc, libxslt-dev]
    override-pull: |
      snapcraftctl pull  
      snapcraftctl set-version "$(git describe --tags)"
    override-build: |
      snapcraftctl build
      sed -i 's/find_library(libname)/"liblept.so.5"/g' $SNAPCRAFT_PART_INSTALL/lib/python3.6/site-packages/ocrmypdf/leptonica.py
    override-prime: |
      snapcraftctl prime
      ln -s ./convert-im6.q16 usr/bin/convert
      ln -sf ../../../../../../../etc/ssl/certs/java/cacerts usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
